name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git "$HOME\depot_tools"

      - name: Build flutter
        env:
          DEPOT_TOOLS_WIN_TOOLCHAIN: "0"
        run: |
          $env:PATH="$HOME\depot_tools;$env:PATH"

          git clone https://github.com/flutter/flutter.git
          cd flutter
          cp engine/scripts/standard.gclient .gclient
          gclient sync

          cd engine/src
          $env:PATH="$(pwd)\flutter\bin;$env:PATH"
          et build --config host_release //flutter/shell/platform/embedder:flutter_engine

          mkdir dist/windows-x64-embedder
          cp out/host_release/flutter_embedder.h      dist/windows-x64-embedder/
          cp out/host_release/flutter_engine.dll      dist/windows-x64-embedder/
          cp out/host_release/flutter_engine.dll.lib  dist/windows-x64-embedder/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-embedder
          path: dist/windows-x64-embedder/*
